"use client"
import React from 'react'
import TambahMenu from '../modal/tambahMenu'
import Cart from './carttest'
const initialKeranjang = {
  1: { menuId: 1, name: "Nasi Goreng", price: 15000, quantity: 2, total: 30000 },
  2: { menuId: 2, name: "Mie Goreng", price: 12000, quantity: 1, total: 12000 },
};
export default function ProfilePage() {
  return (
    <div>
      <a href="#" className='btn btn-circle btn-success' onClick={()=>(document.getElementById("gotodashboard") as HTMLDialogElement).showModal()}>abcde</a>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <div>abcde</div>
      <dialog id="gotodashboard" className="modal modal-backdrop sm:modal-middle">
                  <div className="modal-box text-center">
                  <span className="loading loading-ring loading-lg text-blue-600"></span>
                    <p className="py-4 text-black">
                      Conneting to dashboard...
                    </p>
                    <div className="modal-action">
                      <form method="dialog">
                        {/* if there is a button in form, it will close the modal */}
                        {/* <button className="btn">Close</button> */}
                      </form>
                    </div>
                  </div>
                </dialog>

    </div>
  )
}
